<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── Yoghurt products ──────────────────────────────────────
            [
                'name'          => 'Strawberry Yoghurt',
                'sku'           => 'YOG-STRW-200',
                'category'      => 'yoghurt',
                'flavor'        => 'Strawberry',
                'size_label'    => '200ml',
                'unit'          => 'carton',
                'cost_price'    => 1800.00,
                'selling_price' => 2500.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => '24 cups per carton',
            ],
            [
                'name'          => 'Plain Yoghurt',
                'sku'           => 'YOG-PLAIN-500',
                'category'      => 'yoghurt',
                'flavor'        => 'Plain',
                'size_label'    => '500ml',
                'unit'          => 'carton',
                'cost_price'    => 3200.00,
                'selling_price' => 4500.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => '12 cups per carton',
            ],
            [
                'name'          => 'Mango Yoghurt',
                'sku'           => 'YOG-MANG-200',
                'category'      => 'yoghurt',
                'flavor'        => 'Mango',
                'size_label'    => '200ml',
                'unit'          => 'carton',
                'cost_price'    => 1900.00,
                'selling_price' => 2600.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => null,
            ],
            [
                'name'          => 'Vanilla Yoghurt',
                'sku'           => 'YOG-VAN-1L',
                'category'      => 'yoghurt',
                'flavor'        => 'Vanilla',
                'size_label'    => '1L',
                'unit'          => 'pack',
                'cost_price'    => 2800.00,
                'selling_price' => 4000.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => 'Chilled - store below 8°C',
            ],
            [
                'name'          => 'Chocolate Yoghurt',
                'sku'           => 'YOG-CHOC-200',
                'category'      => 'yoghurt',
                'flavor'        => 'Chocolate',
                'size_label'    => '200ml',
                'unit'          => 'carton',
                'cost_price'    => 2000.00,
                'selling_price' => 2800.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => null,
            ],
            [
                'name'          => 'Mixed Berry Yoghurt',
                'sku'           => 'YOG-MXBR-200',
                'category'      => 'yoghurt',
                'flavor'        => 'Mixed Berry',
                'size_label'    => '200ml',
                'unit'          => 'carton',
                'cost_price'    => 1950.00,
                'selling_price' => 2700.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => 'Currently out of stock - reorder pending',
            ],
            [
                'name'          => 'Zobo Yoghurt',
                'sku'           => 'YOG-ZOBO-200',
                'category'      => 'yoghurt',
                'flavor'        => 'Zobo',
                'size_label'    => '200ml',
                'unit'          => 'carton',
                'cost_price'    => 1750.00,
                'selling_price' => 2500.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => 'Seasonal favourite',
            ],
            [
                'name'          => 'Pineapple Yoghurt',
                'sku'           => 'YOG-PINE-500',
                'category'      => 'yoghurt',
                'flavor'        => 'Pineapple',
                'size_label'    => '500ml',
                'unit'          => 'pack',
                'cost_price'    => 3000.00,
                'selling_price' => 4200.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => null,
            ],

            // ── Packaging ─────────────────────────────────────────────
            [
                'name'          => 'Yoghurt Cups (200ml)',
                'sku'           => 'PKG-CUP-200',
                'category'      => 'packaging',
                'flavor'        => null,
                'size_label'    => '200ml',
                'unit'          => 'carton',
                'cost_price'    => 4500.00,
                'selling_price' => 0.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => '500 cups per carton',
            ],
            [
                'name'          => 'Yoghurt Cups (500ml)',
                'sku'           => 'PKG-CUP-500',
                'category'      => 'packaging',
                'flavor'        => null,
                'size_label'    => '500ml',
                'unit'          => 'carton',
                'cost_price'    => 6500.00,
                'selling_price' => 0.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => '250 cups per carton',
            ],
            [
                'name'          => 'Sealing Foil Roll',
                'sku'           => 'PKG-FOIL-STD',
                'category'      => 'packaging',
                'flavor'        => null,
                'size_label'    => null,
                'unit'          => 'piece',
                'cost_price'    => 12000.00,
                'selling_price' => 0.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => 'Compatible with standard cup sealer',
            ],

            // ── Accessories ───────────────────────────────────────────
            [
                'name'          => 'Plastic Spoons (Bulk)',
                'sku'           => 'ACC-SPOON-BLK',
                'category'      => 'accessories',
                'flavor'        => null,
                'size_label'    => null,
                'unit'          => 'carton',
                'cost_price'    => 2200.00,
                'selling_price' => 3000.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => '1000 spoons per carton',
            ],
            [
                'name'          => 'Insulated Delivery Bag',
                'sku'           => 'ACC-BAG-INS',
                'category'      => 'accessories',
                'flavor'        => null,
                'size_label'    => null,
                'unit'          => 'piece',
                'cost_price'    => 8500.00,
                'selling_price' => 12000.00,
                'quantity'      => 50,
                'reorder_level' => 10,
                'supplier_name' => 'Country Yoghurt',
                'notes'         => 'Keeps products chilled up to 6 hours',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['sku' => $product['sku']], $product);
        }
    }
}
